### ISSUE TITLE
Bug: Release added then removed

### ISSUE THREAD

**Issue by Varming73** [debridmediamanager/zurg-public#76]
I have no idea what is going on in this example. A movie is added and later then removed again. 

2024-02-08T16:32:00.328Z        DEBUG   manager Finished processing fixers
2024-02-08T16:32:07.537Z        DEBUG   manager Output of hook on_library_update:
Detected update on: movies/The.Color.of.Money.1986.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.mkv
Refresh requested for section 18 on path: /media/rdtest/movies/The.Color.of.Money.1986.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.mkv
Detected update on: __all__/The.Color.of.Money.1986.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.mkv
Update does not match specified directories, skipping...
All updated sections refreshed.

```
2024-02-08T16:32:00.328Z        DEBUG   manager Finished processing fixers
2024-02-08T16:32:07.537Z        DEBUG   manager Output of hook on_library_update:
Detected update on: movies/The.Color.of.Money.1986.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.mkv
Refresh requested for section 18 on path: /media/rdtest/movies/The.Color.of.Money.1986.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.mkv
Detected update on: __all__/The.Color.of.Money.1986.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.mkv
Update does not match specified directories, skipping...
All updated sections refreshed.

2024-02-08T16:32:07.537Z        DEBUG   manager Triggered hook on_library_update for 2 path(s)
2024-02-08T16:33:41.103Z        INFO    manager Detected changes! Refreshing 5596 torrents
2024-02-08T16:33:41.873Z        DEBUG   realdebrid      Got 1000 torrents (page 1), total count is 5596
2024-02-08T16:33:42.408Z        DEBUG   realdebrid      Got 2000 torrents (page 2), total count is 5596
2024-02-08T16:33:42.961Z        DEBUG   realdebrid      Got 3000 torrents (page 3), total count is 5596
2024-02-08T16:33:43.563Z        DEBUG   realdebrid      Got 4000 torrents (page 4), total count is 5596
2024-02-08T16:33:44.315Z        DEBUG   realdebrid      Got 5000 torrents (page 5), total count is 5596
2024-02-08T16:33:45.005Z        DEBUG   realdebrid      Got info for torrent 62DHJD4ECBYAA (progress=0%)
2024-02-08T16:33:45.005Z        DEBUG   manager Saved torrent 62DHJD4ECBYAA to file
2024-02-08T16:33:45.064Z        DEBUG   realdebrid      Got info for torrent OZBYNM6N64ON2 (progress=0%)
2024-02-08T16:33:45.064Z        DEBUG   realdebrid      Got info for torrent 43C7RXKWFXWGC (progress=0%)
2024-02-08T16:33:45.065Z        DEBUG   manager Saved torrent OZBYNM6N64ON2 to file
2024-02-08T16:33:45.065Z        DEBUG   manager Saved torrent 43C7RXKWFXWGC to file
2024-02-08T16:33:45.066Z        DEBUG   realdebrid      Got info for torrent QGZ57BSV3Z5M4 (progress=100%)
2024-02-08T16:33:45.067Z        DEBUG   manager Saved torrent QGZ57BSV3Z5M4 to file
2024-02-08T16:33:45.068Z        DEBUG   realdebrid      Got info for torrent 4OBDWXYTZGWKO (progress=100%)
2024-02-08T16:33:45.068Z        DEBUG   realdebrid      Got info for torrent IOWX5SGSSMPLC (progress=0%)
2024-02-08T16:33:45.068Z        DEBUG   manager Saved torrent 4OBDWXYTZGWKO to file
2024-02-08T16:33:45.068Z        DEBUG   manager Saved torrent IOWX5SGSSMPLC to file
2024-02-08T16:33:45.069Z        DEBUG   realdebrid      Got info for torrent RGLOXP33HXMWA (progress=0%)
2024-02-08T16:33:45.069Z        DEBUG   manager Saved torrent RGLOXP33HXMWA to file
2024-02-08T16:33:45.071Z        DEBUG   realdebrid      Got info for torrent ZDR7SC56PCDRC (progress=0%)
2024-02-08T16:33:45.071Z        DEBUG   realdebrid      Got info for torrent 2XRKTXR2WGCX2 (progress=100%)
2024-02-08T16:33:45.071Z        DEBUG   realdebrid      Got info for torrent RGLVIVKMXWSWU (progress=0%)
2024-02-08T16:33:45.071Z        DEBUG   manager Saved torrent ZDR7SC56PCDRC to file
2024-02-08T16:33:45.071Z        DEBUG   realdebrid      Got info for torrent 4N2MTOZ7GOLXW (progress=0%)
2024-02-08T16:33:45.071Z        DEBUG   manager Saved torrent RGLVIVKMXWSWU to file
2024-02-08T16:33:45.071Z        DEBUG   manager Saved torrent 2XRKTXR2WGCX2 to file
2024-02-08T16:33:45.072Z        DEBUG   manager Saved torrent 4N2MTOZ7GOLXW to file
2024-02-08T16:33:45.073Z        DEBUG   realdebrid      Got info for torrent TRMF56ZFTZ4BG (progress=0%)
2024-02-08T16:33:45.073Z        DEBUG   realdebrid      Got info for torrent BHPF43QC6TBZI (progress=0%)
2024-02-08T16:33:45.073Z        DEBUG   manager Saved torrent TRMF56ZFTZ4BG to file
2024-02-08T16:33:45.073Z        DEBUG   manager Saved torrent BHPF43QC6TBZI to file
2024-02-08T16:33:45.075Z        DEBUG   realdebrid      Got info for torrent 5G3ACZZEUP77A (progress=0%)
2024-02-08T16:33:45.075Z        DEBUG   realdebrid      Got info for torrent HDGGYBGWVR7IW (progress=0%)
2024-02-08T16:33:45.075Z        DEBUG   realdebrid      Got info for torrent 7FJPZTPAYNW6K (progress=0%)
2024-02-08T16:33:45.076Z        DEBUG   manager Saved torrent 5G3ACZZEUP77A to file
2024-02-08T16:33:45.076Z        DEBUG   manager Saved torrent HDGGYBGWVR7IW to file
2024-02-08T16:33:45.076Z        DEBUG   manager Saved torrent 7FJPZTPAYNW6K to file
2024-02-08T16:33:45.076Z        DEBUG   realdebrid      Got info for torrent XP34KUQFF3XOA (progress=0%)
2024-02-08T16:33:45.077Z        DEBUG   manager Saved torrent XP34KUQFF3XOA to file
2024-02-08T16:33:45.078Z        DEBUG   realdebrid      Got info for torrent ENZ5H3GIGSCFY (progress=0%)
2024-02-08T16:33:45.078Z        DEBUG   realdebrid      Got info for torrent PO3ITA47S6GQC (progress=0%)
2024-02-08T16:33:45.078Z        DEBUG   manager Saved torrent ENZ5H3GIGSCFY to file
2024-02-08T16:33:45.078Z        DEBUG   manager Saved torrent PO3ITA47S6GQC to file
2024-02-08T16:33:45.079Z        DEBUG   realdebrid      Got info for torrent AVZ2HUZXNDCPA (progress=0%)
2024-02-08T16:33:45.079Z        DEBUG   manager Saved torrent AVZ2HUZXNDCPA to file
2024-02-08T16:33:45.079Z        DEBUG   realdebrid      Got info for torrent MNZKTJIW5X5BO (progress=0%)
2024-02-08T16:33:45.079Z        DEBUG   manager Saved torrent MNZKTJIW5X5BO to file
2024-02-08T16:33:45.080Z        DEBUG   realdebrid      Got info for torrent VQF36ELOLOIVS (progress=21%)
2024-02-08T16:33:45.080Z        DEBUG   realdebrid      Got info for torrent HENIBLKK5D7YU (progress=5%)
2024-02-08T16:33:45.080Z        DEBUG   realdebrid      Got info for torrent 4YXJ6ZCYFUJ2K (progress=100%)
2024-02-08T16:33:45.080Z        DEBUG   manager Saved torrent HENIBLKK5D7YU to file
2024-02-08T16:33:45.080Z        DEBUG   realdebrid      Got info for torrent IURGTQYJOBBEY (progress=0%)
2024-02-08T16:33:45.080Z        DEBUG   manager Saved torrent VQF36ELOLOIVS to file
2024-02-08T16:33:45.080Z        DEBUG   manager Saved torrent 4YXJ6ZCYFUJ2K to file
2024-02-08T16:33:45.081Z        DEBUG   realdebrid      Got info for torrent L3JHLLQWE3QZS (progress=100%)
2024-02-08T16:33:45.081Z        DEBUG   manager Saved torrent IURGTQYJOBBEY to file
2024-02-08T16:33:45.081Z        DEBUG   realdebrid      Got info for torrent NP6MNT74363N2 (progress=0%)
2024-02-08T16:33:45.082Z        DEBUG   realdebrid      Got info for torrent V6SWJ6WSCWX5I (progress=0%)
2024-02-08T16:33:45.082Z        DEBUG   manager Saved torrent NP6MNT74363N2 to file
2024-02-08T16:33:45.082Z        DEBUG   manager Saved torrent V6SWJ6WSCWX5I to file
2024-02-08T16:33:45.083Z        DEBUG   realdebrid      Got info for torrent Q2OWZANHHP2T6 (progress=0%)
2024-02-08T16:33:45.084Z        DEBUG   realdebrid      Got info for torrent 6CWNUUESHEIYC (progress=0%)
2024-02-08T16:33:45.085Z        DEBUG   manager Saved torrent Q2OWZANHHP2T6 to file
2024-02-08T16:33:45.085Z        DEBUG   manager Saved torrent 6CWNUUESHEIYC to file
2024-02-08T16:33:45.087Z        DEBUG   realdebrid      Got info for torrent 24ZL5QC4Z54TG (progress=0%)
2024-02-08T16:33:45.088Z        DEBUG   manager Saved torrent 24ZL5QC4Z54TG to file
2024-02-08T16:33:45.088Z        DEBUG   realdebrid      Got info for torrent 4OT3ZD2AN4OXI (progress=0%)
2024-02-08T16:33:45.088Z        DEBUG   manager Saved torrent L3JHLLQWE3QZS to file
2024-02-08T16:33:45.089Z        DEBUG   manager Saved torrent 4OT3ZD2AN4OXI to file
2024-02-08T16:33:45.096Z        DEBUG   realdebrid      Got info for torrent FKIU56LFSIS4K (progress=100%)
2024-02-08T16:33:45.103Z        DEBUG   manager Saved torrent FKIU56LFSIS4K to file
2024-02-08T16:33:45.141Z        DEBUG   realdebrid      Got info for torrent EBLRLSSSOZSJU (progress=0%)
2024-02-08T16:33:45.142Z        DEBUG   manager Saved torrent EBLRLSSSOZSJU to file
2024-02-08T16:33:45.143Z        DEBUG   realdebrid      Got info for torrent ONKUF6MWWNW3O (progress=0%)
2024-02-08T16:33:45.144Z        DEBUG   manager Saved torrent ONKUF6MWWNW3O to file
2024-02-08T16:33:45.144Z        DEBUG   realdebrid      Got info for torrent HJYGLFELUDRKW (progress=0%)
2024-02-08T16:33:45.145Z        DEBUG   manager Saved torrent HJYGLFELUDRKW to file
2024-02-08T16:33:45.145Z        DEBUG   realdebrid      Got info for torrent MAOERD4J7KLM4 (progress=0%)
2024-02-08T16:33:45.145Z        DEBUG   realdebrid      Got info for torrent G2Q4RS65QV3WS (progress=0%)
2024-02-08T16:33:45.145Z        DEBUG   realdebrid      Got info for torrent HMKBBSZVKBWBW (progress=0%)
2024-02-08T16:33:45.145Z        DEBUG   manager Saved torrent MAOERD4J7KLM4 to file
2024-02-08T16:33:45.145Z        DEBUG   manager Saved torrent G2Q4RS65QV3WS to file
2024-02-08T16:33:45.145Z        DEBUG   manager Saved torrent HMKBBSZVKBWBW to file
2024-02-08T16:33:45.146Z        DEBUG   realdebrid      Got info for torrent BSTJSWLAR2BEU (progress=0%)
2024-02-08T16:33:45.147Z        DEBUG   manager Saved torrent BSTJSWLAR2BEU to file
2024-02-08T16:33:45.147Z        DEBUG   realdebrid      Got info for torrent F65262EAFEDFE (progress=0%)
2024-02-08T16:33:45.147Z        DEBUG   manager Saved torrent F65262EAFEDFE to file
2024-02-08T16:33:45.149Z        DEBUG   realdebrid      Got info for torrent 3P3JS4XZVHAJM (progress=0%)
2024-02-08T16:33:45.150Z        DEBUG   manager Saved torrent 3P3JS4XZVHAJM to file
2024-02-08T16:33:45.150Z        DEBUG   realdebrid      Got info for torrent LQ7B5LO6YT27K (progress=0%)
2024-02-08T16:33:45.150Z        DEBUG   manager Saved torrent LQ7B5LO6YT27K to file
2024-02-08T16:33:45.152Z        DEBUG   realdebrid      Got info for torrent IO6R7MJCZV3YQ (progress=0%)
2024-02-08T16:33:45.153Z        DEBUG   manager Saved torrent IO6R7MJCZV3YQ to file
2024-02-08T16:33:45.153Z        DEBUG   realdebrid      Got info for torrent AJP3YT3RE6I5K (progress=0%)
2024-02-08T16:33:45.153Z        DEBUG   manager Saved torrent AJP3YT3RE6I5K to file
2024-02-08T16:33:45.155Z        DEBUG   realdebrid      Got info for torrent IQY4KEPH2O2EK (progress=0%)
2024-02-08T16:33:45.156Z        DEBUG   manager Saved torrent IQY4KEPH2O2EK to file
2024-02-08T16:33:45.157Z        DEBUG   realdebrid      Got info for torrent KQSPS3YMDJNXC (progress=0%)
2024-02-08T16:33:45.157Z        DEBUG   realdebrid      Got info for torrent 2QW5YXKRM5WL4 (progress=0%)
2024-02-08T16:33:45.157Z        DEBUG   manager Saved torrent KQSPS3YMDJNXC to file
2024-02-08T16:33:45.157Z        DEBUG   manager Saved torrent 2QW5YXKRM5WL4 to file
2024-02-08T16:33:45.157Z        DEBUG   realdebrid      Got info for torrent VFG2RADHUURMS (progress=0%)
2024-02-08T16:33:45.158Z        DEBUG   manager Saved torrent VFG2RADHUURMS to file
2024-02-08T16:33:45.158Z        DEBUG   realdebrid      Got info for torrent HR2XMF7BELS3W (progress=0%)
2024-02-08T16:33:45.159Z        DEBUG   manager Saved torrent HR2XMF7BELS3W to file
2024-02-08T16:33:45.161Z        DEBUG   realdebrid      Got info for torrent PUWHPZIJFHINI (progress=0%)
2024-02-08T16:33:45.161Z        DEBUG   manager Saved torrent PUWHPZIJFHINI to file
2024-02-08T16:33:45.161Z        DEBUG   realdebrid      Got info for torrent 3SRBQNRA3WIRA (progress=0%)
2024-02-08T16:33:45.161Z        DEBUG   manager Saved torrent 3SRBQNRA3WIRA to file
2024-02-08T16:33:45.162Z        DEBUG   realdebrid      Got info for torrent QQJ4W66BJSHA4 (progress=0%)
2024-02-08T16:33:45.162Z        DEBUG   manager Saved torrent QQJ4W66BJSHA4 to file
2024-02-08T16:33:45.163Z        DEBUG   realdebrid      Got info for torrent CTCSGSJ3RHZ6G (progress=0%)
2024-02-08T16:33:45.163Z        DEBUG   manager Saved torrent CTCSGSJ3RHZ6G to file
2024-02-08T16:33:45.163Z        DEBUG   realdebrid      Got info for torrent QJJBAF5HCVGPW (progress=0%)
2024-02-08T16:33:45.163Z        DEBUG   manager Saved torrent QJJBAF5HCVGPW to file
2024-02-08T16:33:45.166Z        DEBUG   realdebrid      Got info for torrent EXU5VSLL2CXJA (progress=0%)
2024-02-08T16:33:45.166Z        DEBUG   manager Saved torrent EXU5VSLL2CXJA to file
2024-02-08T16:33:45.168Z        DEBUG   realdebrid      Got info for torrent T4TNR6RYXD2DM (progress=0%)
2024-02-08T16:33:45.169Z        DEBUG   realdebrid      Got info for torrent PVA5F7CPTV5PA (progress=0%)
2024-02-08T16:33:45.169Z        DEBUG   manager Saved torrent T4TNR6RYXD2DM to file
2024-02-08T16:33:45.169Z        DEBUG   manager Saved torrent PVA5F7CPTV5PA to file
2024-02-08T16:33:45.173Z        DEBUG   realdebrid      Got info for torrent CDFWQGCAHUSAA (progress=0%)
2024-02-08T16:33:45.173Z        DEBUG   manager Saved torrent CDFWQGCAHUSAA to file
2024-02-08T16:33:45.177Z        DEBUG   realdebrid      Got info for torrent Y34TXKQLHSHJM (progress=0%)
2024-02-08T16:33:45.178Z        DEBUG   realdebrid      Got info for torrent X2FO2CRQ2L6AI (progress=0%)
2024-02-08T16:33:45.178Z        DEBUG   manager Saved torrent Y34TXKQLHSHJM to file
2024-02-08T16:33:45.178Z        DEBUG   manager Saved torrent X2FO2CRQ2L6AI to file
2024-02-08T16:33:45.179Z        DEBUG   realdebrid      Got info for torrent JZDZ5WYT5VZRM (progress=0%)
2024-02-08T16:33:45.180Z        DEBUG   manager Saved torrent JZDZ5WYT5VZRM to file
2024-02-08T16:33:45.181Z        DEBUG   realdebrid      Got info for torrent MKZYHW5II4R6W (progress=0%)
2024-02-08T16:33:45.181Z        DEBUG   realdebrid      Got info for torrent RSHTX5LIX7X2K (progress=0%)
2024-02-08T16:33:45.181Z        DEBUG   manager Saved torrent MKZYHW5II4R6W to file
2024-02-08T16:33:45.181Z        DEBUG   manager Saved torrent RSHTX5LIX7X2K to file
2024-02-08T16:33:45.217Z        DEBUG   realdebrid      Got info for torrent YQIDTUQ5UT3ES (progress=0%)
2024-02-08T16:33:45.218Z        DEBUG   manager Saved torrent YQIDTUQ5UT3ES to file
2024-02-08T16:33:45.223Z        DEBUG   realdebrid      Got info for torrent 76DSJJHRTGP6C (progress=0%)
2024-02-08T16:33:45.224Z        DEBUG   manager Saved torrent 76DSJJHRTGP6C to file
2024-02-08T16:33:45.227Z        DEBUG   realdebrid      Got info for torrent KY7JSNYSOAVC4 (progress=0%)
2024-02-08T16:33:45.228Z        DEBUG   manager Saved torrent KY7JSNYSOAVC4 to file
2024-02-08T16:33:45.229Z        DEBUG   realdebrid      Got info for torrent YHNWXBLXC6DCA (progress=0%)
2024-02-08T16:33:45.230Z        DEBUG   manager Saved torrent YHNWXBLXC6DCA to file
2024-02-08T16:33:45.230Z        INFO    manager Fetched info for 5596 torrents
2024-02-08T16:33:45.237Z        INFO    manager Compiled into 5568 torrents, 0 were missing info
2024-02-08T16:33:45.238Z        INFO    manager Removing torrent The.Color.of.Money.1986.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.mkv from zurg database (not real-debrid)
2024-02-08T16:33:45.238Z        INFO    manager Finished refreshing torrents
2024-02-08T16:33:45.238Z        DEBUG   manager Processing fixers (22 left)
2024-02-08T16:33:45.239Z        DEBUG   manager Finished processing fixers
2024-02-08T16:33:50.240Z        DEBUG   manager Output of hook on_library_update:
All updated sections refreshed.
```

Why is the movie suddenly removed? I just checked RD and it's gone from there too.

**Comment by yowmamasita** [comment]
idk, if zurg deletes a torrent, it will show a specific log line but I don't see it here

**Comment by ajitid** [comment]
Slightly related: Any idea why when a torrent is deleted zurg doesn't sends the show/movie path to `plex_update.sh` script as an argument? The script runs on removal of a torrent but doesn't do anything because of this.

**Comment by Varming73** [comment]
@yowmamasita I went back to hotfix7 and added the same release. This time the release didn't disappear again so it's not because the release has been taken down it seems.

**Comment by TEALC82** [comment]
Hello @Varming73 , in .3-hf7 you no longer have the problem updating the zurg file? thx

**Comment by b4154** [comment]
Experiencing the same issue. Downgrading to hf7 fixed it.

**Comment by yowmamasita** [comment]
This should be fixed in the latest version

**Comment by shrimpyuk** [comment]
> This should be fixed in the latest version

I'm still getting this on hf11 as well as hf7. Unsure why it's happening

**Comment by brandodando** [comment]
I'm getting that same "removing from database" error on v0.9.3-final.

**Comment by yowmamasita** [comment]
Closing this as superseded. A release being added and then removed again was three separate loops, all of which were found and fixed on 14 September 2026, more than two years after you filed this.

The short version: a dead link that zurg had given up on was being taken back on the next refresh because the wrong kind of success cleared the give-up, archive-interior files were being condemned for holding no link of their own, and a verified archive link was vouching for files it could not see. Any of the three made a healthy release flap in and out.

If you still see anything like it on a current build, say so and this reopens.
